name: 'Semantic Release Action'
description:
  'Runs `semantic-release`. Respects .releaserc.js in your repo. Exports version variables for you
  to use in subsequent actions.'
author: 'codfish'
branding:
  icon: 'arrow-up-right'
  color: 'orange'
inputs:
  branch:
    description:
      'The branch on which releases should happen.
      https://github.com/semantic-release/semantic-release/blob/master/docs/usage/configuration.md#branch'
outputs:
  new-release-published:
    description:
      "Either `'true'` when a new release was published or `'false'` when no release was published"
  release-version:
    description: "The new releases' semantic version, i.e. `1.8.3`"
  release-major:
    description: "The new releases' major version number, i.e. `1`"
  release-minor:
    description: "The new releases' minor version number, i.e. `8`"
  release-patch:
    description: "The new releases' patch version number, i.e. `3`"
runs:
  using: 'docker'
  image: 'Dockerfile'
