name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    needs: validate

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: semantic-release
        id: semantic
        uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: test output
        if: steps.semantic.outputs.new-release-published == 'true'
        run: |
          echo "$OUTPUTS"
          echo "$NEW_RELEASE_PUBLISHED"
          echo "$RELEASE_MAJOR"
          echo "$RELEASE_MINOR"
          echo "$RELEASE_PATCH"
        env:
          OUTPUTS: ${{ toJson(steps.semantic.outputs) }}
