name: Validate

on: pull_request

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - run: npm ci

      - run: npm run lint

      # dog-food testing. Should not release here at all, cause it's not on
      # master.
      - name: semantic-release
        id: semantic
        uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: test output
        if: steps.semantic.outputs.new-release-published == 'false'
        run: |
          echo "$OUTPUTS"
          echo "should be false: $NEW_RELEASE_PUBLISHED"
          echo "should be empty: $RELEASE_MAJOR"
          echo "should be empty: $RELEASE_MINOR"
          echo "should be empty: $RELEASE_PATCH"
        env:
          OUTPUTS: ${{ toJson(steps.semantic.outputs) }}
